### ISSUE TITLE
No denoiser yet?

### ISSUE THREAD

**Issue by gaetandezeiraud** [TheRealMJP/DXRPathTracer#14]
No denoiser yet? Do you advice about them?

**Comment by TheRealMJP** [comment]
No, unfortunately I haven't had time to try integrating a denoiser for this. For a different project I've had some success with Nvidia's ray tracing denoiser: [https://github.com/NVIDIAGameWorks/RayTracingDenoiser](https://github.com/NVIDIAGameWorks/RayTracingDenoiser)

In that case I was using it to denoise real-time direct lighting using ReSTIR, but it could potentially also work for path tracer like this.

**Comment by gaetandezeiraud** [comment]
Thank you for the answer and your time!
That helps me a lot.
