### ISSUE TITLE
Error compiling shader file "RayTrace.hlsl" ,error : 'sampler.hlsl' not found

### ISSUE THREAD

**Issue by SeokYeChan** [TheRealMJP/DXRPathTracer#5]
I cloned repo and just build&run DXRPathTracer.sln 
However, It could not find the include path and it did not work properly.

![image](https://user-images.githubusercontent.com/36983662/60235375-7e451c00-98e2-11e9-9671-f3529a12c846.png)

how to run this?

**Comment by TheRealMJP** [comment]
So all of the shaders are supposed to be compiled with an include directory that points to `DXRPathTracer\SampleFramework12\v1.02\Shaders`. I'm guessing that something is going wrong with how that include directory gets set up, perhaps an issue with Unicode handling. I would stick a breakpoint on line 292 of ShaderCompilation.cpp and step through that too if anything looks off. If you can't figure it out, you could try just hard-coding `expandedFrameworkShaderDir` to the full path of the directory,

**Comment by zhangbo0037** [comment]
I also got this error, but the path "expandedFrameworkShaderDir" looks like right ...

**Comment by zhangbo0037** [comment]
@TheRealMJP I figured out this shader issue. 
but when I run this solution, I got a new problem :
 " DXRPathTracer.exe has triggered a break point" in the line 314 of ShaderCompilation.cpp file. 
This means there is a problem when compiling shader "RayTrace.hlsl".

However, I did not get any detailed error messege about where is the mistake ...
How should I debug this ? thanks

**Comment by masahi** [comment]
Hi, I also met this issue. Removing the following two comments worked for me.

https://github.com/TheRealMJP/DXRPathTracer/blob/master/SampleFramework12/v1.02/Shaders/Sampling.hlsl#L24
https://github.com/TheRealMJP/DXRPathTracer/blob/master/SampleFramework12/v1.02/Shaders/Sampling.hlsl#L78

**Comment by zhangbo0037** [comment]
oh my god！thank you so much.&nbsp;
unblieveval you send email to me 😭
Im your fans，and I usually learn graphics from your blog.&nbsp;
Tomorrow I will try your method in school.&nbsp;
have a nice day！

发自我的iPhone


------------------ Original ------------------

**Comment by zhangbo0037** [comment]
> Hi, I also met this issue. Removing the following two comments worked for me.
> 
> https://github.com/TheRealMJP/DXRPathTracer/blob/master/SampleFramework12/v1.02/Shaders/Sampling.hlsl#L24
> https://github.com/TheRealMJP/DXRPathTracer/blob/master/SampleFramework12/v1.02/Shaders/Sampling.hlsl#L78

Thank you so much , I will try it tomorrow, have a nice day!

**Comment by TheRealMJP** [comment]
Hey everyone, did removing those comments work for you? It's really strange that those comments caused DXC to fail to find the include, but I guess I've seen stranger things. If that fix works I'll make the change and submit it.

**Comment by masahi** [comment]
Yes, the error message is confusing. The problem was what looks like '^' character there doesn't seem to be a "valid" character in Japanese / Chinese settings. I think it is a UTF issue.

**Comment by zhangbo0037** [comment]
> Hey everyone, did removing those comments work for you? It's really strange that those comments caused DXC to fail to find the include, but I guess I've seen stranger things. If that fix works I'll make the change and submit it.

Yes, the solution of masahi works for me well. The language of my VS2017 I setup to English, and my computer language is korean, but I'm chinese student ....... Does codes of note part (green color) in shader are compiled ？

**Comment by TheRealMJP** [comment]
Ok, I just submitted a change to remove the comments that seemed to be causing the issue. Thank you everyone that helped track this down! I'll close this for now, but let me know if you're still having this problem after pulling latest.
